[project]
name = "glassdoor-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.12.0",
    "chromium>=0.0.0",
    "click>=8.1.0",
    "fake-useragent>=1.4.0",
    "lxml>=4.9.0",
    "playwright>=1.40.0",
    "pydantic>=2.5.0",
    "pytest-playwright>=0.7.2",
    "python-dotenv>=1.0.0",
    "requests>=2.31.0",
    "rich>=13.7.0",
]
